version: '3.7'

services:
  # traefik will auto route on this context path. expect steakmon will listen on bare slash  
  steakmon:
    build: .
    restart: always
    networks:
      - isengard

networks:
  isengard:
    external: True
